# Generated by Django 4.1.6 on 2023-02-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urldata',
            name='urlapp',
        ),
        migrations.AddField(
            model_name='urldata',
            name='file',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='urldata',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='urldata',
            name='url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
