# Generated by Django 4.1.6 on 2023-02-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_data_rename_app_urldata_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
