# Generated by Django 4.1.6 on 2023-02-20 12:07

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_urldata_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, null=True)),
        ),
    ]
