# Generated by Django 4.1.6 on 2023-02-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_urldata_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urldata',
            name='url',
        ),
        migrations.AddField(
            model_name='urldata',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
