# Generated by Django 4.1.6 on 2023-02-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_urldata_url_urldata_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=400, null=True)),
                ('file', models.FileField(null=True, upload_to='uploads/')),
                ('slug', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='UrlData',
        ),
    ]
