# Generated by Django 4.1.6 on 2023-02-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_filedata_delete_data_delete_urldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
